// Nombres ficticios por región (se combinan al azar: ningún jugador es una persona real)
const P={
es:['Lucas Mateo Tomás Franco Nicolás Agustín Bruno Joaquín Santiago Ramiro Facundo Gonzalo Ezequiel Julián Matías Emiliano Lautaro Bautista Federico Thiago Ignacio Leandro Gastón Cristian Diego Sergio Andrés Iván Álvaro Hugo Pablo Rafael Adrián Marcos Óscar Rubén Samuel','Acosta Benítez Cabrera Domínguez Escobar Figueroa Godoy Herrera Ibarra Juárez Luna Medina Navarro Ojeda Paz Quiroga Ramírez Sosa Torres Urquiza Vega Ledesma Barrios Correa Díaz Fernández Giménez Molina Ortiz Rojas Silva Vargas Castro Morales Ríos Salazar Peña Campos Aguirre Suárez'],
pt:['Gabriel Lucas Mateus Pedro Rafael Guilherme Thiago Bruno Diego Felipe Caio Vinícius Rodrigo Leandro Gustavo Henrique Danilo Fábio Marcelo Renato João Tiago Rui Nuno Hélder André Ricardo Sérgio Davi Enzo Murilo Igor Otávio Wesley Yuri','Silva Santos Oliveira Souza Lima Pereira Costa Ferreira Rodrigues Almeida Nascimento Carvalho Araújo Ribeiro Gomes Martins Barbosa Rocha Dias Moreira Cardoso Teixeira Correia Mendes Nunes Freitas Pinto Monteiro Fonseca Duarte Batista Moura Cunha Lopes'],
en:['James Jack Harry Oliver Charlie George Thomas Daniel Ryan Liam Connor Callum Jordan Dean Luke Ben Sam Adam Ethan Mason Tyler Noah Aaron Kyle Shane Grant Scott Craig Declan Reece Jamie Josh Mark Paul Kevin Brandon Austin','Smith Jones Taylor Brown Wilson Evans Walker Wright Roberts Johnson Hall Wood Clarke Turner Hughes Edwards Green Hill Moore Cooper Ward Morgan Baker Bell King Lewis Murphy Kelly Reid Fraser Campbell Bennett Russell Hayes Foster Brooks Mills'],
de:['Lukas Leon Finn Jonas Felix Maximilian Paul Tim Niklas Jan Moritz Fabian Julian Tobias Marcel Kevin Dennis Patrick Florian Sebastian Matthias Stefan Philipp Simon Erik Nils Lars Johannes Benedikt Robin Kai','Müller Schmidt Schneider Fischer Weber Meyer Wagner Becker Schulz Hoffmann Koch Richter Klein Wolf Neumann Schwarz Zimmermann Braun Krüger Hofmann Hartmann Lange Werner Krause Lehmann Köhler Maier Huber Keller Bauer Vogel Frank Berger'],
fr:['Lucas Hugo Louis Jules Théo Nathan Enzo Mathis Maxime Antoine Baptiste Clément Romain Kévin Florian Anthony Quentin Alexis Adrien Yanis Rayan Samuel Julien Damien Benoît Thibault Étienne Mehdi Idriss Moussa Ibrahim Cédric','Martin Bernard Dubois Thomas Robert Richard Petit Durand Leroy Moreau Simon Laurent Lefebvre Michel Garcia David Bertrand Roux Vincent Fournier Morel Girard André Mercier Dupont Lambert Bonnet François Martinez Legrand Garnier Faure Rousseau'],
it:['Luca Marco Matteo Andrea Alessandro Lorenzo Davide Simone Federico Riccardo Gabriele Francesco Giovanni Stefano Filippo Nicola Antonio Salvatore Vincenzo Emanuele Daniele Fabio Claudio Paolo Massimo Cristian Michele Enrico Tommaso Pietro Samuele','Rossi Russo Ferrari Esposito Bianchi Romano Colombo Ricci Marino Greco Bruno Gallo Conti De Luca Mancini Costa Giordano Rizzo Lombardi Moretti Barbieri Fontana Santoro Mariani Rinaldi Caruso Ferrara Galli Martini Leone Longo Gentile Villa'],
nl:['Daan Sem Lucas Milan Levi Luuk Thijs Jesse Bram Ruben Joost Sven Niels Tom Stijn Mees Finn Jelle Koen Max Tim Wouter Dennis Rick Mitchell Gijs Floris Hidde Ties Jorrit','De Jong Jansen De Vries Van den Berg Van Dijk Bakker Janssen Visser Smit Meijer De Boer Mulder De Groot Bos Vos Peters Hendriks Van Leeuwen Dekker Brouwer De Wit Dijkstra Smits De Graaf Kok Jacobs Van der Meer Verhoeven Prins Huisman'],
nord:['Erik Lars Anders Mikael Johan Magnus Henrik Oskar Emil Sven Nils Jonas Kasper Mads Rasmus Søren Jesper Morten Torben Bjørn Ole Kristian Sindre Håkon Eirik Jens Mattias Viktor Axel Gustav Elias Lasse Teemu','Andersen Nielsen Hansen Pedersen Larsen Sørensen Rasmussen Jørgensen Eriksson Johansson Karlsson Svensson Lindqvist Berg Holm Dahl Lund Bakke Haugen Johansen Olsen Kristiansen Halvorsen Strand Nyberg Virtanen Korhonen Mäkinen Laine Heikkinen Gunnarsson Jónsson Sigurdsson'],
slw:['Jakub Jan Tomáš Marek Michał Piotr Paweł Kamil Adam Łukasz Dawid Krzysztof Marcin Filip Ondřej Lukáš Martin Peter Matej Luka Marko Andrej Jure Ivan Josip Mario Domagoj Tin Dino Boris','Nowak Kowalski Wiśniewski Wójcik Kowalczyk Kamiński Lewandowski Zieliński Szymański Dvořák Novák Svoboda Černý Procházka Kováč Horváth Varga Novotný Marković Horvat Kovačić Babić Jurić Knežević Petrović Bošnjak Zupan Potočnik Krajnc Kos'],
sle:['Ivan Dmitri Sergei Aleksandr Andrei Nikolai Pavel Maksim Artem Oleg Viktor Yuri Roman Denis Vladislav Bogdan Taras Mykola Stefan Nemanja Dušan Miloš Luka Aleksa Nikola Vuk Marko Darko Goran Zoran Petar Radoslav Todor Hristo','Ivanov Petrov Smirnov Kuznetsov Popov Sokolov Lebedev Kozlov Novikov Morozov Volkov Shevchenko Bondarenko Kovalenko Boyko Tkachenko Kravchenko Petrović Jovanović Nikolić Ilić Đorđević Stojanović Pavlović Georgiev Dimitrov Stoyanov Todorov Popović Kostić Mitrović'],
ro:['Andrei Mihai Alexandru Cristian Bogdan Răzvan Florin Ionuț Gabriel Marius Adrian Ștefan Daniel Dorin László Gábor Balázs Zoltán Attila Péter Tamás Ádám Dávid Norbert Csaba Levente Ferenc Béla Roland Máté','Popescu Ionescu Popa Stan Dumitru Gheorghe Constantin Marin Radu Stoica Munteanu Toma Nagy Kovács Tóth Szabó Horváth Varga Kiss Molnár Németh Farkas Balogh Papp Takács Juhász Lakatos Mészáros Oláh Simon Rácz']
,gr:['Giorgos Nikos Dimitris Kostas Yannis Panagiotis Christos Thanasis Vasilis Stelios Alexandros Andreas Michalis Petros Antonis Eleftherios Marios Savvas Kyriakos Stavros Arben Besnik Dritan Fatos Ilir Kujtim Gentian Valon Endrit Besian','Papadopoulos Georgiou Nikolaidis Dimitriou Konstantinou Vasiliou Karagiannis Ioannou Papadakis Antoniou Christodoulou Makris Hoxha Gjoni Shehu Krasniqi Berisha Morina Gashi Dervishi Kelmendi Basha Hysa Leka Prifti Tafa Rama Cela Dajti Bardhi']
,tr:['Mehmet Mustafa Ahmet Ali Hüseyin Emre Burak Can Cem Kerem Murat Oğuz Yusuf Serkan Barış Tolga Onur Hakan Volkan Eren Deniz Kaan Arda Berkay Rashad Elnur Farid Timur Rustam Aziz Bekzod Jasur Nurlan','Yılmaz Kaya Demir Şahin Çelik Yıldız Yıldırım Öztürk Aydın Özdemir Arslan Doğan Kılıç Aslan Çetin Kara Koç Kurt Özkan Şimşek Polat Mammadov Aliyev Hasanov Huseynov Karimov Rakhimov Ismoilov Tursunov Nazarov Saidov']
,ar:['Mohamed Ahmed Mahmoud Omar Khaled Hassan Youssef Ibrahim Abdullah Ali Karim Tarek Walid Sami Nasser Faisal Hamza Bilal Amine Rachid Mehdi Salim Zakaria Reza Hossein Mehrdad Saeed Ehsan Majid Yasser Nabil Anwar','Al-Farsi Al-Hassan Al-Saadi Haddad Mansour Nasser Abdallah Khalil Saleh Hamdan Said Aziz Benali Bouzid Cherif Messaoudi Trabelsi Ben Salah Jebali Hakimi Ziyech Alavi Hosseini Karimi Rezaei Ahmadi Mousavi Jafari Tehrani Rahimi Farahani']
,ka:['Giorgi Levan Nika Davit Irakli Zurab Lasha Tornike Gela Vakhtang Aram Armen Gevorg Karen Narek Hayk Tigran Artur Sargis Vahe','Beridze Kapanadze Gelashvili Maisuradze Lomidze Chkheidze Kvaratskhelia Mamardashvili Sargsyan Hovhannisyan Grigoryan Harutyunyan Petrosyan Avetisyan Danielyan Mkhitaryan Manukyan']
,jp:['Haruto Yuto Sota Yuki Kenta Takumi Ryota Daiki Shota Kaito Riku Hiroki Naoki Kazuki Masato Taiga Ren Sho Tsubasa Koki','Sato Suzuki Takahashi Tanaka Watanabe Ito Yamamoto Nakamura Kobayashi Kato Yoshida Yamada Sasaki Matsumoto Inoue Kimura Hayashi Shimizu Mori Ikeda']
,kr:['Min-jun Seo-jun Do-yun Ji-hoon Hyun-woo Jun-seo Sung-min Tae-yang Dong-hyun Jae-won Woo-jin Seung-woo Kang-in Hee-chan Young-gwon','Kim Lee Park Choi Jung Kang Cho Yoon Jang Lim Han Oh Seo Shin Kwon Hwang Ahn Song Hong Jeon']
,cn:['Wei Jun Hao Lei Ming Jie Yang Bo Chen Long Peng Tao Xin Kai Yu Fei Hui Qiang Gang Zhen','Wang Li Zhang Liu Chen Yang Huang Zhao Wu Zhou Xu Sun Ma Zhu Hu Guo He Lin Gao Luo']
,sea:['Somchai Anan Nattapong Kritsada Teerasil Minh Hung Duc Quang Tuan Nam Hieu Hafiz Aiman Faizal Syafiq Rizky Dimas Bagas Andika Arif Jose Juan Carlo Miguel Sokha Dara Vichet Kaung Aung','Srisai Jaidee Chaiyasit Nguyen Tran Le Pham Hoang Vo Bui Abdullah Ismail Rahman Hassan Putra Wijaya Santoso Pratama Saputra Cruz Reyes Santos Garcia Dela Rosa Sok Chea Kim Tan Lim Lee']
,in:['Rahul Amit Sandeep Rohit Vikram Arjun Sunil Anil Manish Suresh Ravi Karan Aditya Nikhil Gurpreet Harpreet Imran Faisal Bilal Usman Ali Tariq Shakib Rashed Mahbub Sujan Kamal Nuwan Kasun Tenzin Ibrahim','Sharma Verma Singh Kumar Gupta Patel Reddy Nair Menon Das Roy Khan Ahmed Malik Hussain Sheikh Chowdhury Islam Rahman Hossain Perera Silva Fernando Dorji Wangchuk Thapa Gurung Rai Shrestha Mohamed']
,afo:['Kwame Kofi Yaw Kwabena Emeka Chinedu Obinna Ikenna Tunde Segun Femi Sadio Mamadou Ousmane Ibrahima Moussa Seydou Cheikh Idrissa Boubacar Drissa Issouf Yacouba Didier Serge Jean Patrice Arnaud','Mensah Owusu Boateng Asante Addo Okafor Eze Nwosu Adeyemi Balogh Okoye Diallo Traoré Keita Sow Ndiaye Diop Camara Sissoko Konaté Coulibaly Ouattara Koné Bamba Kouassi Yao Tchamba Mbarga Eto']
,afe:['Brian Kevin Dennis Moses Isaac Joseph Peter Samuel Simon Patrick Emmanuel Yusuf Hassan Abdi Mohamud Tesfaye Dawit Yonas Haile Kidus Amos Elias Juma Baraka Rashid Themba Sipho Thabo Lucky Tendai Tatenda Farai Blessing','Otieno Odhiambo Mwangi Kamau Kiprono Wanjiru Mutua Ssemakula Opio Okello Tumusiime Mugisha Nshimiyimana Hakizimana Bekele Tadesse Alemu Girma Gebre Mohamed Ali Ndlovu Dlamini Nkosi Khumalo Mokoena Moyo Sibanda Chirwa Banda Phiri Mwale Tembo']
,pac:['Jack Ben Liam Ryan Josh Jake Cooper Blake Luke Ethan Tane Rawiri Manu Sione Tevita Josefa Jone Ratu Semi Isoa Rangi Aroha Waka Kele Poutini','Smith Jones Williams Brown Taylor Wilson Moana Tamihana Ngata Hohepa Wiremu Tuilagi Fa\'asavalu Tupou Lolohea Vaka Ravu Naqelevuki Waqa Tagicakibau Tuiasosopo Pouono Taumoepeau Fonua Lavaka']
};
const G={es:'ESP MEX CHI COL PAR PER ECU BOL VEN URU CRC GUA HON SLV PAN NCA CUB DOM PUR EQG ARG',pt:'POR BRA ANG MOZ CPV GNB STP TLS',en:'ENG SCO WAL NIR IRL USA CAN JAM TRI BRB BAH BER CAY GRN LCA VIN ATG SKN DMA VGB VIR AIA TCA MSR BLZ GUY GIB GUM',de:'GER AUT SUI LIE',fr:'FRA BEL LUX AND HAI GLP MTQ GUF MAD MRI SEY COM CHA CTA CGO COD GAB DJI BDI RWA MLI BFA NIG SEN GUI TOG BEN CIV CMR',it:'ITA SMR MLT',nl:'NED SUR CUW ARU SXM',nord:'DEN SWE NOR FIN ISL FRO EST LVA LTU',slw:'POL CZE SVK SVN CRO BIH MNE',sle:'RUS UKR BLR BUL SRB MKD KAZ MDA',ro:'ROU HUN',gr:'GRE CYP ALB KOS',tr:'TUR AZE UZB TKM KGZ TJK',ar:'SAU ARE QAT KUW BHR OMA IRN IRQ JOR SYR LBN PLE YEM EGY MAR ALG TUN LBY MTN SDN AFG ISR',ka:'GEO ARM',jp:'JPN',kr:'KOR PRK',cn:'CHN HKG MAC TPE MNG',sea:'THA VIE MAS IDN SGP PHI MYA CAM LAO BRU',in:'IND PAK BAN NEP SRI BHU MDV',afo:'NGA GHA GAM SLE LBR',afe:'KEN TAN UGA ETH ERI SOM SSD ZAM ZIM RSA NAM BOT LES SWZ MWI',pac:'AUS NZL PNG FIJ SOL VAN NCL TAH SAM TGA COK ASA'};
const MAP={};for(const[g,l]of Object.entries(G))for(const c of l.split(' '))MAP[c]=g;
const ps=g=>{const[a,b]=P[g];return[a.split(' '),b.split(' ')]};
export const grupoDe=cod=>MAP[cod]||'es';
const cache={};
export function pool(cod){const g=grupoDe(cod);return cache[g]||(cache[g]=ps(g))}
export function nombre(cod){const[f,l]=pool(cod);return f[Math.random()*f.length|0]+' '+l[Math.random()*l.length|0]}
