import {CFG} from './config.js';
import {FORMATIONS,OPTIONS,LBL,autoLineup,coords,setFormation} from './tactics.js';
import {badge,hue,face,kit} from './visual.js';
import {Pitch,tacticBoard} from './pitch.js';
import {squadOf,squadValue,wageBill,staffCost} from './clubs.js';
import {LiveMatch} from './matches.js';
import {fmt} from './players.js';
import {Game} from './game.js';
import {save,load} from './save.js';
import * as T from './transfers.js';
import {endSeason,renew} from './season.js';
import * as F from './facilities.js';
import * as SP from './sponsors.js';
import * as IV from './investors.js';
import * as S from './scouting.js';
import * as CP from './comp.js';
import * as CH from './charts.js';
import * as U9 from './ui9.js';
import * as U10 from './ui10.js';
import * as PD from './predio.js';
import * as MU from './mundo.js';
import * as PRM from './premios.js';
import {zl,proyeccion,ingresoProy,refPrice,mantAnual,tvAnual,attendance,nivelOf} from './finance.js';
const MENU=[['sec','Club'],['inicio','🏠','Inicio'],['noticias','📰','Noticias'],['competiciones','🌎','Competiciones'],['plantilla','👥','Plantilla'],['vestuario','👔','Vestuario'],['tacticas','📋','Tácticas'],['entrenamiento','🏃','Entrenamiento'],['calendario','📅','Calendario'],['resultados','⚽','Resultados'],['liga','🏆','Liga'],['sec','Fichajes'],['mercado','💱','Mercado'],['scouting','🔭','Scouting'],['cantera','🌱','Cantera'],['comparar','⚖️','Comparador'],['sec','Negocios'],['mundo2','🌍','Mundo'],['predio','🏞️','Predio'],['instalaciones','🏗️','Instalaciones'],['patrocinios','🤝','Patrocinios'],['inversionistas','💼','Inversionistas'],['finanzas','💰','Finanzas'],['mundo','🌍','Club y mundo'],['sec','Carrera'],['carrera','🧭','Entrenador'],['seleccion','FLAG','Selección'],['premios','🥇','Premios'],['logros','🏅','Logros'],['salon','🏛️','Salón de la fama'],['historia','📈','Historia y gráficos'],['sec','Sistema'],['editor','✏️','Editor de datos'],['guardar','⚙️','Partida y ajustes']];
const POSORD=['POR','DFC','LI','LD','MCD','MC','MCO','MI','MD','EI','ED','DC'];
const COLS=[['vel','VEL'],['ace','ACE'],['pas','PAS'],['tec','TEC'],['tir','TIR'],['def','DEF'],['fis','FIS'],['res','RES'],['men','MEN']];
const CI={entradas:'Entradas',palcos:'Palcos',sponsors:'Patrocinios',tv:'Derechos de TV',merch:'Tienda y merchandising',premios:'Premios y bonos',ventas:'Venta de jugadores',inversores:'Inversionistas',sueldos:'Sueldos',staff:'Cuerpo técnico',mant:'Mantenimiento',obras:'Obras y mejoras',fichajes:'Compra de jugadores',deuda:'Deuda y recompras',socios:'Parte del socio',fondo:'Fondo de derechos'};
const AT=v=>`<span class="at" style="--c:${Math.max(0,Math.min(120,(v-35)*2.1))}">${v}</span>`;
const bar=(v)=>`<span class="bar"><i style="width:${Math.round(Math.min(100,v)*.6)}px;background:hsl(${Math.max(0,Math.min(120,(v-35)*2.1))} 70% 48%)"></i><b>${v}</b></span>`;
const chip=pos=>`<span class="pos p${S.lineaDe(pos)}">${pos}</span>`;
const pips=(n,tope)=>`<div class="pips">${Array.from({length:10},(_,i)=>`<i class="${i<n?'on':i>=tope?'lock':''}"></i>`).join('')}</div>`;
const formChips=f=>`<span class="form">${(f||[]).map(x=>`<i class="${x}">${x==='V'?'G':x==='E'?'E':'P'}</i>`).join('')||'<small class="muted">sin partidos</small>'}</span>`;
const dias=(a,b)=>Math.max(0,Math.round((new Date(b)-new Date(a))/864e5));
const pTable=(ps,extra,g)=>{const fog=g&&g.fog;return`<div class="tw"><table><tr><th>Pos</th><th>Nombre</th><th>Edad</th><th>OVR</th><th>POT</th>${COLS.map(c=>`<th class="hm">${c[1]}</th>`).join('')}<th class="hm">Rasgo</th><th>MOR</th><th>CON</th><th class="hm">Salario</th><th class="hm">Valor</th><th class="hm">Contrato</th>${extra?'<th></th>':''}</tr>${ps.map(p=>{const v=g?S.vista(g,p):{ovr:p.ovr,pot:p.pot,exacto:true};return`<tr class="${p.lesion>0?'inj':''}"><td>${chip(p.pos)}</td><td><span class="av">${face(p,24)}</span><a class="plink" data-act="card" data-id="${p.id}">${p.nombre}</a>${p.lesion>0?` 🩹 ${p.tipo||''} ${p.lesion}d`:''}${p.fondo?' 📑':''}</td><td>${p.edad}</td><td>${v.exacto?bar(p.ovr):`<b>${S.txtOvr(v.ovr)}</b>`}</td><td>${v.exacto?p.pot:`<span class="muted">${S.txtOvr(v.pot)}</span>`}</td>${COLS.map(c=>`<td class="hm">${v.exacto?AT(p[c[0]]):'<span class="muted">?</span>'}</td>`).join('')}<td class="hm">${p.rasgo||''}</td><td>${p.mor}</td><td>${Math.round(p.cond)}</td><td class="hm">${fmt(p.sal)}</td><td class="hm">${fmt(p.val)}</td><td class="hm">${p.contrato}</td>${extra?`<td>${extra(p)}</td>`:''}</tr>`}).join('')}</table></div>`};
const opts=(a,v)=>a.map(x=>`<option ${x==v?'selected':''}>${x}</option>`).join('');
export class UI{
 constructor(el){this.el=el;this.view='inicio';this.f={pos:'',q:'',min:0};this.jr=null;this.sd='';this.lv=null;this.lm=null;
  const clk=e=>{const b=e.target.closest('[data-act]');if(b)this.act(b.dataset.act,b.dataset)};el.addEventListener('click',clk);document.getElementById('dlg').addEventListener('click',clk);
  el.addEventListener('change',e=>{const b=e.target.closest('[data-chg]');if(b)this.chg(b.dataset.chg,b.dataset,b.value)})}
 get g(){return this.game}
 tn(id){const c=this.g.clubs[id]||this.g.ext.clubs[id];return c?c.nombre:'Club desaparecido'}
 toast(m){const t=document.getElementById('toast');t.textContent=m;t.className='show';clearTimeout(this._t);this._t=setTimeout(()=>t.className='',3500)}
 start(){this.game=null;this.el.innerHTML=`<div class="start"><h1>Manager Argentina <small>v1.3</small></h1><p>Elegí tu club. Todos los datos son ficticios.</p>${hasSave()?'<p><button data-act="load">Cargar partida</button></p>':''}<label>División<select data-chg="sd"><option value="">Todas</option>${opts(this.data.leagues.map(l=>l.nombre),this.sd)}</select></label><div class="tw"><table><tr><th>Club</th><th>Ciudad</th><th>División</th><th>Reputación</th><th>Presupuesto</th><th>Plantilla</th><th></th></tr>${this.data.clubs.filter(c=>!this.sd||c.division==this.sd).map(c=>`<tr><td>${badge(c,22)} ${c.nombre}</td><td>${c.ciudad}, ${c.provincia}</td><td>${c.division}</td><td>${c.reputacion}</td><td>${fmt(c.presupuesto)}</td><td>${fmt(c.valorPlantilla)}</td><td><button data-act="pick" data-id="${c.id}">Elegir</button></td></tr>`).join('')}</table></div></div>`}
 render(){const g=this.g,c=g.clubs[g.userClubId];this.theme();const al=g.spOfertas.length+g.invOfertas.length+g.ofertas.length;
  this.el.innerHTML=`<aside class="side"><div class="brand">${badge(c,40)}<div>${c.nombre}<small>${g.date} · ${c.division}</small></div></div>${MENU.map(([k,i,t])=>k==='sec'?`<div class="sec">${i}</div>`:`<button class="${k==this.view?'on':''}" data-act="nav" data-v="${k}"><i>${i==='FLAG'?g.pais.bandera:i}</i>${t}${k==='mercado'&&g.ofertas.length?`<span class="dot">${g.ofertas.length}</span>`:''}${k==='patrocinios'&&g.spOfertas.length?`<span class="dot">${g.spOfertas.length}</span>`:''}${k==='inversionistas'&&g.invOfertas.length?`<span class="dot">${g.invOfertas.length}</span>`:''}</button>`).join('')}</aside><main>${this['v_'+this.view]()}</main>`;if(this.view==='tacticas')this.initTP()}
 theme(){let t='dark';try{t=localStorage.getItem('fm_theme')||'dark'}catch(e){}const r=document.documentElement;r.dataset.theme=t;r.style.setProperty('--h',this.game?hue(this.g.clubs[this.g.userClubId]):150)}
 v_inicio(){const g=this.g;if(g.despedido)return`<h2>Te despidieron</h2><p>La directiva perdió la confianza en vos. Podés empezar una nueva carrera en otro club.</p><p><button class="pri" data-act="new">Nueva partida</button></p>`;
  const c=g.clubs[g.userClubId],L=g.league,m=(L.fixtures[L.j]||[]).find(x=>x.h==c.id||x.a==c.id),srt=L.sorted(),pos=srt.findIndex(r=>r.id==c.id)+1,li=L.results.findLastIndex(r=>r.h==c.id||r.a==c.id),rival=m?g.clubs[m.h==c.id?m.a:m.h]:null,rt=srt.find(r=>r.id==c.id),
  nc=CP.proximoUser(g),sq=squadOf(g,c.id),lesion=sq.filter(p=>p.lesion>0),vence=g.expiring(),proy=ingresoProy(g,c),ok=pos<=g.objetivo.max,
  lo=Math.max(0,Math.min(srt.length-7,pos-4)),mini=srt.slice(lo,lo+7);
  return`<div class="hero">${badge(c,64)}<div><h2>${c.nombre}</h2><small>${g.year} · ${c.division} · ${c.estadio}</small></div><div style="margin-left:auto;text-align:right">${rival?`<small>Próximo · Jornada ${L.j+1} (${L.date(L.j)})</small><div class="vs">${m.h==c.id?'vs':'@'} ${rival.nombre}</div>`:'<div class="vs">Temporada finalizada</div>'}${nc?`<div style="margin-top:6px"><small>${CP.NOMBRES[nc.c.key]} · ${nc.fecha}</small><div>${nc.m.h==c.id?'vs':'@'} ${this.tn(nc.m.h==c.id?nc.m.a:nc.m.h)}</div></div>`:''}</div></div>
  ${g.allDone?`<div class="alert">Terminaron todas las ligas. Contratos por vencer: ${vence.length}. <button class="pri" data-act="endseason">Cerrar temporada</button></div>`:`<p><button class="pri" data-act="next">▶ Jugar hasta la próxima jornada</button> <button data-act="day">Avanzar un día</button> <button data-act="livetog">Partidos en vivo: ${g.live?'sí':'no'}</button></p>`}
  ${IV.deudaAlta(g)?'<div class="alert b">⚠️ Tu deuda es muy alta: la directiva no autoriza fichajes hasta que la bajes.</div>':''}${g.spOfertas.length?`<div class="alert">🤝 Tenés ${g.spOfertas.length} oferta(s) de patrocinio esperando respuesta.</div>`:''}${g.invOfertas.length?`<div class="alert">💼 Tenés ${g.invOfertas.length} propuesta(s) de inversionistas.</div>`:''}
  <div class="cards"><div><b>Posición</b>${pos}º de ${L.ids.length}<small class="${ok?'good':'badc'}">Objetivo: top ${g.objetivo.max}</small></div><div><b>Presupuesto</b><span class="${c.presupuesto<0?'badc':''}">${fmt(c.presupuesto)}</span><small>Ingreso anual proyectado ${fmt(proy)}</small></div><div><b>Confianza</b>${g.confianza}/100<div class="meter ${g.confianza<35?'red':g.confianza<55?'amb':''}"><i style="width:${g.confianza}%"></i></div></div><div><b>Forma</b>${formChips(c.forma)}<small>${rt?`${rt.pts} pts · ${rt.gf}-${rt.gc}`:''}</small></div><div><b>Plantilla</b>${sq.length} jugadores<small>${lesion.length} lesionados · ${vence.length} contratos por vencer</small></div></div>
  <div class="g2"><div><h3>Tabla</h3>${this.tabla(L,mini,srt)}</div><div><h3>Último partido</h3>${li>=0?this.resRow(L.results[li],li):'<p class="muted">Todavía no jugaste.</p>'}<h3>Obras en curso</h3>${c.obras.length?c.obras.map(o=>`<div class="kv"><span>${F.zonas().find(z=>z.id===o.zona).nombre} → nivel ${o.a}</span><b>${dias(g.date,o.hasta)} días</b></div>`).join(''):'<p class="muted">Ninguna.</p>'}<h3>Novedades</h3>${g.news.slice(-7).reverse().map(n=>`<div class="kv"><span>${n}</span></div>`).join('')}</div></div>`}
 tabla(L,rows,all){const g=this.g,n=all.length,nv=L.def.nivel;return`<div class="tw"><table><tr><th>#</th><th>Club</th><th>PJ</th><th>DG</th><th>Pts</th></tr>${rows.map(r=>{const i=all.indexOf(r),z=i<(nv===1?1:2)?'zup':nv===1&&i<4?'zcont':nv<5&&i>=n-2?'zdown':'';return`<tr class="${z} ${r.id==g.userClubId?'hl':''}"><td>${i+1}</td><td>${badge(g.clubs[r.id],18)} ${this.tn(r.id)}</td><td>${r.pj}</td><td>${r.gf-r.gc}</td><td><b>${r.pts}</b></td></tr>`}).join('')}</table></div>`}
 v_plantilla(){const g=this.g;return`<h2>Plantilla</h2><p class="hint">📑 = derechos vendidos a un fondo. Colores: verde = alto, rojo = bajo.</p>${pTable([...squadOf(g,g.userClubId)].sort((a,b)=>POSORD.indexOf(a.pos)-POSORD.indexOf(b.pos)||b.ovr-a.ovr),p=>`${p.contrato<=g.year+1?`<button data-act="renew" data-id="${p.id}">Renovar</button> `:''}<button data-act="follow" data-id="${p.id}" style="display:none"></button>`)}`}
 v_liga(){const g=this.g,L=g.leagues[this.lv]||g.league,srt=L.sorted(),gs=Object.values(g.players).filter(p=>p.gol&&g.clubs[p.clubId]?.liga==L.def.id).sort((a,b)=>b.gol-a.gol).slice(0,5),nv=L.def.nivel;
  return`<h2>${L.def.nombre}</h2><label style="max-width:260px">Liga<select data-chg="lv">${Object.values(g.leagues).map(l=>`<option value="${l.def.id}" ${l===L?'selected':''}>${l.def.nombre}</option>`).join('')}</select></label><div class="legend"><span><i style="background:var(--ok)"></i>${nv===1?'Campeón':'Ascenso'}</span>${nv===1?'<span><i style="background:var(--info)"></i>Clasificación continental (v0.8)</span>':''}${nv<5?'<span><i style="background:var(--bad)"></i>Descenso</span>':''}</div>
  <div class="tw"><table><tr><th>#</th><th>Club</th><th>PJ</th><th>G</th><th>E</th><th>P</th><th>GF</th><th>GC</th><th>DG</th><th>Pts</th><th>Forma</th></tr>${srt.map((r,i)=>{const z=i<(nv===1?1:2)?'zup':nv===1&&i<4?'zcont':nv<5&&i>=srt.length-2?'zdown':'';return`<tr class="${z} ${r.id==g.userClubId?'hl':''}"><td>${i+1}</td><td>${badge(g.clubs[r.id],20)} ${this.tn(r.id)}</td><td>${r.pj}</td><td>${r.g}</td><td>${r.e}</td><td>${r.p}</td><td>${r.gf}</td><td>${r.gc}</td><td>${r.gf-r.gc}</td><td><b>${r.pts}</b></td><td>${formChips(g.clubs[r.id].forma)}</td></tr>`}).join('')}</table></div><h3>Goleadores</h3>${gs.map(p=>`<div class="kv"><span>${p.nombre} (${this.tn(p.clubId)})</span><b>${p.gol}</b></div>`).join('')||'<p>Sin goles todavía.</p>'}<h3>Campeones de Primera</h3>${g.hist.map(h=>`<div class="kv"><span>${h.y}</span><b>${h.camp}</b></div>`).join('')||'<p>Todavía no hay temporadas completas.</p>'}`}
 v_mercado(){const g=this.g,f=this.f,c=g.clubs[g.userClubId],res=T.search(g,{pos:f.pos,q:f.q,min:+f.min});
  return`<h2>Mercado</h2><p>Presupuesto: <b>${fmt(c.presupuesto)}</b> · Plantilla: ${c.plantilla.length}/30 · Tope salarial: <b>${fmt(c.topeSalarial)}</b> (usado ${fmt(wageBill(g,c.id))})</p>${IV.deudaAlta(g)?'<div class="alert b">Deuda demasiado alta: no podés fichar.</div>':''}${g.fog?'<p class="hint">🌫️ Niebla de información activa: de los jugadores de otros clubes ves rangos estimados. Mandá ojeadores o seguí jugadores (☆) para afinar la estimación.</p>':''}<div class="grid"><label>Posición<select data-chg="f" data-k="pos"><option value="">Todas</option>${opts(POSORD,f.pos)}</select></label><label>OVR mínimo<input type="number" data-chg="f" data-k="min" value="${f.min}"></label><label>Nombre<input data-chg="f" data-k="q" value="${f.q}"></label></div>${g.ofertas.length?`<h3>Ofertas recibidas</h3>${g.ofertas.map((o,i)=>`<div class="res">${this.tn(o.club)} ofrece <b>${fmt(o.monto)}</b> por ${g.players[o.pid].nombre} <button class="pri" data-act="offer" data-i="${i}" data-ok="1">Aceptar</button> <button data-act="offer" data-i="${i}" data-ok="0">Rechazar</button></div>`).join('')}`:''}<h3>Jugadores disponibles</h3>${pTable(res,p=>`<small>${p.clubId?this.tn(p.clubId):'Libre'}</small> <button data-act="follow" data-id="${p.id}" title="Seguir">${g.seguir.includes(p.id)?'★':'☆'}</button> <input id="o${p.id}" type="number" step="10000" value="${p.val}" style="width:100px"> <button class="pri" data-act="buy" data-id="${p.id}">Ofertar</button>${p.clubId?` <button data-act="loan" data-id="${p.id}">Préstamo</button>`:''}`,g)}<h3>Vender</h3>${pTable(squadOf(g,c.id),p=>`<button data-act="sell" data-id="${p.id}">Vender</button> <button data-act="loanout" data-id="${p.id}">Prestar</button>${p.prestamo?' (en préstamo)':''}`)}`}
 v_scouting(){const g=this.g,c=g.clubs[g.userClubId],mx=S.maxScouts(g),R=CFG.scouts,
  seg=g.seguir.map(i=>g.players[i]).filter(Boolean);
  return`<h2>Scouting</h2><div class="cards"><div><b>Oficina de scouting</b>Nivel ${zl(c,'scouting')}<small>Hasta ${mx} ojeadores</small></div><div><b>Ojeadores</b>${g.scouts.length}/${mx}<small>Sueldos: ${fmt(g.scouts.reduce((a,s)=>a+s.sal,0))}/año</small></div><div><b>Niebla de información</b>${g.fog?'Activada':'Desactivada'}<small><button data-act="fog">Cambiar</button></small></div></div>
  <p><button class="pri" data-act="sc_hire">Contratar ojeador</button> <span class="hint">El nivel del ojeador (1-5) se descubre al contratarlo. Más nivel = informes más precisos y misiones más rápidas.</span></p>
  <div class="g2">${g.scouts.map(s=>`<div class="card"><h4>🔭 ${s.nombre} <small class="muted">nivel ${s.nivel} · ${fmt(s.sal)}/año</small></h4>${s.mision?`<p>En misión: <b>${s.mision.region}</b> · ${S.TIPOS[s.mision.tipo]}${s.mision.linea?' · '+S.LINEAS[s.mision.linea]:''}<br>Vuelve en ${dias(g.date,s.mision.fin)} días</p><div class="row"><button data-act="sc_cancel" data-id="${s.id}">Cancelar</button></div>`:`<div class="grid"><label>Región<select id="sr${s.id}">${R.regiones.map(r=>`<option>${r}</option>`).join('')}</select></label><label>Buscar<select id="st${s.id}">${Object.entries(S.TIPOS).map(([k,v])=>`<option value="${k}">${v}</option>`).join('')}</select></label><label>Posición<select id="sl${s.id}"><option value="">Cualquiera</option>${Object.entries(S.LINEAS).map(([k,v])=>`<option value="${k}">${v}</option>`).join('')}</select></label></div><div class="row"><button class="pri" data-act="sc_go" data-id="${s.id}">Enviar de misión</button> <button class="bad" data-act="sc_fire" data-id="${s.id}">Despedir</button></div>`}</div>`).join('')||'<p class="muted">No tenés ojeadores. Contratá uno para empezar a recibir informes.</p>'}</div>
  <h3>Jugadores seguidos</h3>${seg.length?pTable(seg,p=>`<small>${this.tn(p.clubId)||'Libre'}</small> <button data-act="follow" data-id="${p.id}">★ Dejar</button>`,g):'<p class="muted">Seguí jugadores desde el mercado o los informes con ☆.</p>'}
  <h3>Informes recientes</h3>${g.informes.length?`<div class="tw"><table><tr><th>Fecha</th><th>Jugador</th><th>Pos</th><th>Edad</th><th>Club</th><th>OVR est.</th><th>POT est.</th><th>Precisión</th><th></th></tr>${g.informes.slice(0,25).map(i=>{const p=g.players[i.pid],v=p?S.vista(g,p):null;return`<tr><td>${i.fecha}</td><td>${i.nombre}</td><td>${chip(i.pos)}</td><td>${i.edad}</td><td>${p&&p.clubId?this.tn(p.clubId):'Libre'}</td><td><b>${v?S.txtOvr(v.ovr):S.txtOvr(i.ovr)}</b></td><td>${v?S.txtOvr(v.pot):S.txtOvr(i.pot)}</td><td>${Math.round(((g.conocido[i.pid])||0)*100)}%</td><td><button data-act="follow" data-id="${i.pid}">${g.seguir.includes(i.pid)?'★':'☆'}</button></td></tr>`}).join('')}</table></div>`:'<p class="muted">Sin informes todavía.</p>'}
  <h3>Promesas para la cantera</h3><div class="g2">${g.promesas.slice(-12).reverse().map(x=>{const v=S.vistaPromesa(g,x);return`<div class="card"><h4>${chip(x.p.pos)} ${x.p.nombre} <small class="muted">${x.p.edad} años</small></h4><p>${x.region} · OVR <b>${S.txtOvr(v.ovr)}</b> · POT <b>${S.txtOvr(v.pot)}</b></p><div class="row"><b>${fmt(x.precio)}</b><button class="pri" data-act="promo" data-id="${x.sid}">Incorporar</button></div></div>`}).join('')}</div>`}
 v_instalaciones(){const g=this.g,c=g.clubs[g.userClubId],tope=F.topeZona(g,c),Z=F.zonas(),rows=[['entrenador','Entrenador','Mejora el entrenamiento y el desarrollo de los jóvenes.'],['ayudante','Ayudante','Ayuda a recuperar la moral más rápido tras una derrota.'],['preparadorFisico','Preparador físico','Menos lesiones y menos cansancio.']];
  return`<h2>Instalaciones</h2><div class="cards"><div><b>Nivel máximo por división</b>${tope}<small>${c.division}: ascendé para construir más</small></div><div><b>Obras</b>${c.obras.length}/${CFG.facilities.obrasMax}</div><div><b>Mantenimiento anual</b>${fmt(mantAnual(c))}</div><div><b>Presupuesto</b>${fmt(c.presupuesto)}</div></div>
  <div class="g2">${Z.map(z=>{const lv=zl(c,z.id),ob=c.obras.find(o=>o.zona===z.id);return`<div class="card"><h4>${z.icono} ${z.nombre} <small class="muted">nivel ${lv}</small></h4>${pips(lv,tope)}<p>${z.desc}</p>${ob?`<p class="warn">🏗️ Obra a nivel ${ob.a}: faltan ${dias(g.date,ob.hasta)} días</p>`:`<div class="row">${lv>=tope?`<span class="muted">${lv>=10?'Máximo':'Tope de tu división'}</span>`:`<button class="pri" data-act="obra" data-k="${z.id}">Mejorar · ${fmt(this.zc(c,z))}</button><small class="muted">${F.obraDias(lv)} días</small>`}</div>`}</div>`}).join('')}</div>
  <h3>Cuerpo técnico</h3><div class="g2">${rows.map(([k,t,d])=>`<div class="card"><h4>${t} <small class="muted">${c.cuerpoTecnico[k]}/100</small></h4><div class="meter"><i style="width:${c.cuerpoTecnico[k]}%"></i></div><p>${d}</p><div class="row"><button data-act="staffup" data-k="${k}">Mejorar +5 · ${fmt(F.staffUpCost(c,k))}</button></div></div>`).join('')}</div>`}
 zc(c,z){return Math.round(z.costo*(zl(c,z.id)+1)**2*Math.pow(c.reputacion/62,1.5)/1000)*1000}
 v_patrocinios(){const g=this.g,tot=Object.values(g.contratos).reduce((s,x)=>s+x.anual,0);
  return`<h2>Patrocinios</h2><div class="cards"><div><b>Ingreso anual por sponsors</b>${fmt(tot)}<small>Se cobra por jornada</small></div><div><b>Espacios libres</b>${SP.vacios(g).length}/4</div></div>
  <div class="g2">${SP.SLOTS.map(s=>{const k=g.contratos[s];return`<div class="card"><h4>${SP.SLOT_NOMBRE[s]}</h4>${k?`<p><b>${k.nombre}</b> <span class="muted">(${k.rubro})</span></p><div class="kv"><span>Paga por año</span><b>${fmt(k.anual)}</b></div><div class="kv"><span>Vence</span><b>${k.hasta}</b></div><p class="hint">Bonos: objetivo +${Math.round(k.bonos.obj*100)}% · campeón +${Math.round(k.bonos.camp*100)}% · ascenso +${Math.round(k.bonos.asc*100)}%. Si descendés, baja ${Math.round(k.pen*100)}%.</p>`:'<p class="muted">Espacio libre. Esperá ofertas de marcas.</p>'}</div>`}).join('')}</div>
  <h3>Ofertas recibidas</h3>${g.spOfertas.map(o=>`<div class="card"><h4>${o.nombre} <small class="muted">${o.rubro} · ${SP.SLOT_NOMBRE[o.slot]}</small></h4><div class="kv"><span>Paga por año</span><b>${fmt(o.anual)}</b></div><div class="kv"><span>Duración</span><b>${o.anios} ${o.anios>1?'temporadas':'temporada'}</b></div><div class="kv"><span>Bonos</span><span>obj +${Math.round(o.bonos.obj*100)}% · camp +${Math.round(o.bonos.camp*100)}% · asc +${Math.round(o.bonos.asc*100)}%</span></div><div class="kv"><span>Cláusula de descenso</span><span>-${Math.round(o.pen*100)}%</span></div><div class="kv"><span>Vence en</span><span>${dias(g.date,o.vence)} días</span></div><div class="row"><button class="pri" data-act="sp_ok" data-id="${o.id}">Aceptar</button><button data-act="sp_no" data-id="${o.id}">Rechazar</button>${o.neg?'<small class="muted">Ya negociada</small>':`<button data-act="sp_neg" data-id="${o.id}" data-p="0.1">Pedir +10%</button><button data-act="sp_neg" data-id="${o.id}" data-p="0.25">+25%</button><button data-act="sp_neg" data-id="${o.id}" data-p="0.5">+50%</button>`}</div></div>`).join('')||'<p class="muted">No hay ofertas por ahora. Las marcas se acercan cuando hay espacios libres.</p>'}`}
 v_inversionistas(){const g=this.g,c=g.clubs[g.userClubId],lim=IV.limiteDeuda(g),d=IV.deuda(g),r=lim?d/lim:0;
  return`<h2>Inversionistas</h2><div class="cards"><div><b>Deuda actual</b>${fmt(d)}<div class="meter ${r>.8?'red':r>.5?'amb':''}"><i style="width:${Math.min(100,r*100)}%"></i></div><small>Límite ${fmt(lim)}${IV.deudaAlta(g)?' · sin fichajes':''}</small></div><div><b>Presupuesto</b>${fmt(c.presupuesto)}</div></div>
  <h3>Acuerdos vigentes</h3>${g.invs.map(x=>`<div class="card"><h4>${x.nombre} <small class="muted">${IV.TIPOS[x.tipo]}</small></h4><p>${this.invTxt(x,true)}</p><div class="row"><button class="bad" data-act="inv_buy" data-id="${x.id}">Terminar acuerdo · ${fmt(IV.costoRecompra(g,x))}</button></div></div>`).join('')||'<p class="muted">Sin acuerdos.</p>'}
  <h3>Propuestas</h3>${g.invOfertas.map(o=>`<div class="card"><h4>${o.nombre} <small class="muted">${IV.TIPOS[o.tipo]}</small></h4><p>${o.desc}</p><p>${this.invTxt(o)}</p><div class="row"><button class="pri" data-act="inv_ok" data-id="${o.id}">Aceptar</button><button data-act="inv_no" data-id="${o.id}">Rechazar</button><small class="muted">Vence en ${dias(g.date,o.vence)} días</small></div></div>`).join('')||'<p class="muted">No hay propuestas por ahora.</p>'}`}
 invTxt(o,v){const m=fmt(o.monto);switch(o.tipo){case'prestamo':return v?`Resta pagar ${fmt(o.restante)} (cuotas por jornada).`:`Recibís ${m}. Devolvés ${fmt(o.total)} en ${o.anios} años (interés ${Math.round(o.interes*1000)/10}% anual).`;
  case'socio':return`${v?'Aportó':'Aporta'} ${m} a cambio de ${Math.round(o.pct*100)}% de tus ventas de jugadores durante ${o.anios} años.`;
  case'mecenas':return`${v?'Aportó':'Aporta'} ${m}. Exige terminar entre los primeros ${o.exigeMax} cada temporada y veta la venta de tus 3 mejores jugadores. Dura ${o.anios} años. Si no cumplís, baja la confianza de la directiva.`;
  default:return`Paga ${m} por ${Math.round(o.pct*100)}% de los derechos de ${o.pnombre}. Cuando lo vendas, le corresponde ese porcentaje.`}}
 v_finanzas(){const g=this.g,c=g.clubs[g.userClubId],w=wageBill(g,c.id),pr=proyeccion(g,c),J=g.league.fixtures.length,ing=Object.entries(c.fin.ing),gas=Object.entries(c.fin.gas),ti=ing.reduce((s,x)=>s+x[1],0),tg=gas.reduce((s,x)=>s+x[1],0),
  col=['#34d399','#60a5fa','#fbbf24','#f472b6','#a78bfa','#fb923c','#2dd4bf','#f87171','#94a3b8'],
  stack=(a,t)=>`<div class="stk">${a.map((x,i)=>`<i title="${CI[x[0]]}" style="width:${t?x[1]/t*100:0}%;background:${col[i%col.length]}"></i>`).join('')}</div>`,
  lst=(a,t)=>a.sort((x,y)=>y[1]-x[1]).map(([k,v],i)=>`<div class="kv"><span><i style="display:inline-block;width:9px;height:9px;border-radius:3px;background:${col[i%col.length]};margin-right:6px"></i>${CI[k]||k}</span><b>${fmt(v)}</b></div>`).join(''),
  rp=refPrice(g,c),att=attendance(g,c,{ciudad:'',provincia:'',reputacion:c.reputacion}).att,
  prT=Object.values(pr).reduce((s,x)=>s+x,0),gT=w+staffCost(c)+mantAnual(c)+g.scouts.reduce((s,x)=>s+x.sal,0);
  return`<h2>Finanzas</h2><div class="cards"><div><b>Presupuesto</b><span class="${c.presupuesto<0?'badc':''}">${fmt(c.presupuesto)}</span></div><div><b>Resultado de la temporada</b><span class="${ti-tg>=0?'good':'badc'}">${fmt(ti-tg)}</span><small>${fmt(ti)} ingresos · ${fmt(tg)} gastos</small></div><div><b>Masa salarial</b>${fmt(w)}<small>Tope: ${fmt(c.topeSalarial)}</small><div class="meter ${w/c.topeSalarial>.95?'red':w/c.topeSalarial>.8?'amb':''}"><i style="width:${Math.min(100,w/c.topeSalarial*100)}%"></i></div></div><div><b>Valor de plantilla</b>${fmt(squadValue(g,c.id))}</div></div>
  <div class="g2"><div class="card"><h4>🎟️ Precio de entradas</h4><p>Precio actual: <b>$${(rp*c.precio).toFixed(2)}</b> (referencia $${rp.toFixed(2)}) · multiplicador x${c.precio.toFixed(2)}</p><input type="range" min="0.5" max="1.8" step="0.05" value="${c.precio}" data-chg="precio"><p class="hint">Precio alto: más ingreso por entrada pero menos público. Con el estadio lleno podés subirlo sin perder gente. Asistencia estimada (rival medio): ${att.toLocaleString('es-AR')} de ${c.capacidad.toLocaleString('es-AR')}.</p></div>
  <div class="card"><h4>📈 Proyección anual</h4>${Object.entries(pr).map(([k,v])=>`<div class="kv"><span>${CI[k]}</span><b>${fmt(v)}</b></div>`).join('')}<div class="kv"><span><b>Total ingresos</b></span><b>${fmt(prT)}</b></div><div class="kv"><span>Gastos fijos (sueldos, staff, mant., scouts)</span><b>${fmt(gT)}</b></div></div></div>
  <div class="g2"><div><h3>Ingresos de la temporada</h3>${stack(ing,ti)}${lst(ing,ti)||'<p class="muted">Todavía sin movimientos.</p>'}</div><div><h3>Gastos de la temporada</h3>${stack(gas,tg)}${lst(gas,tg)||'<p class="muted">Todavía sin movimientos.</p>'}</div></div>
  <h3>Historial por temporada</h3>${g.finHist.length?`<div class="tw"><table><tr><th>Temporada</th><th>Ingresos</th><th>Gastos</th><th>Resultado</th><th>Entradas</th><th>Sponsors</th><th>TV</th><th>Sueldos</th></tr>${[...g.finHist].reverse().map(h=>{const a=Object.values(h.ing).reduce((s,x)=>s+x,0),b=Object.values(h.gas).reduce((s,x)=>s+x,0);return`<tr><td>${h.y}</td><td>${fmt(a)}</td><td>${fmt(b)}</td><td class="${a-b>=0?'good':'badc'}">${fmt(a-b)}</td><td>${fmt(h.ing.entradas||0)}</td><td>${fmt(h.ing.sponsors||0)}</td><td>${fmt(h.ing.tv||0)}</td><td>${fmt(h.gas.sueldos||0)}</td></tr>`}).join('')}</table></div>`:'<p class="muted">Se arma al cerrar la primera temporada.</p>'}`}
 tieRow(t){const g=this.g,u=g.userClubId,me=t.a===u||t.b===u,f=m=>m.done?`${m.hg}-${m.ag}`:'-';
  const sc=t.ms.length===1?`<b>${t.ms[0].done?f(t.ms[0]):this.fd(t.ms[0].date)}</b>`:`<b>${t.ms.map(m=>m.done?`${this.tn(m.h).slice(0,3)} ${f(m)}`:this.fd(m.date)).join(' · ')}</b>`;
  return`<div class="tie ${me?'me':''}"><span class="${t.w===t.a?'win':t.w!=null?'lose':''}">${this.bd(t.a)} ${this.tn(t.a)}</span>${sc}<span class="${t.w===t.b?'win':t.w!=null?'lose':''}">${this.tn(t.b)} ${this.bd(t.b)}</span>${t.agg&&t.ms.length>1?`<small class="muted">global ${t.agg[0]}-${t.agg[1]}</small>`:''}${t.pen?`<small class="muted">pen. ${t.pen[0]}-${t.pen[1]}</small>`:''}</div>`}
 bd(id){const c=this.g.clubs[id]||this.g.ext.clubs[id];return c?badge(c,18):''}
 fd(d){return d.slice(8)+'/'+d.slice(5,7)}
 v_competiciones(){const g=this.g,k=this.ct||'copa',c=g.comps[k],u=g.userClubId,tabs=['copa','lib','sud'].map(x=>`<button class="${x==k?'on':''}" data-act="ctab" data-k="${x}">${CP.NOMBRES[x]}</button>`).join('');
  if(c.omitida)return`<h2>Competiciones</h2><div class="tabs">${tabs}</div><p class="muted">Esta competición no se juega en la temporada en curso porque la partida venía avanzada. Arranca en la próxima.</p>`;
  const mine=CP.matchesUser(g,c),cn=id=>this.tn(id);
  let h=`<h2>Competiciones</h2><div class="tabs">${tabs}</div><div class="cards"><div><b>${c.nombre} ${g.year}</b>${c.done?'Finalizada':'En juego'}<small>${c.equipos.length} equipos</small></div><div><b>Tu participación</b>${CP.alcance(g,k)}</div><div><b>${c.done?'Campeón':'Fase actual'}</b>${c.done?cn(c.campeon):(c.rondas.at(-1)?.nombre||(c.tipo==='gko'?'Fase de grupos':'-'))}</div></div>`;
  if(mine.length)h+=`<h3>Tus partidos</h3><div class="tw"><table><tr><th>Fecha</th><th>Ronda</th><th>Partido</th><th>Resultado</th></tr>${mine.map(m=>{const r=(g.reps||[]).find(x=>x.mid===m.id&&x.key===k);return`<tr><td>${m.date}</td><td>${m.md?'Grupos · F'+m.md:(c.rondas.find(r=>r.ties.some(t=>t.ms.includes(m)))?.nombre||'')}</td><td>${cn(m.h)} vs ${cn(m.a)}</td><td>${m.done?`${m.hg}-${m.ag}${r?` <button data-act="reprc" data-m="${m.id}" data-k="${k}">Ver</button>`:''}`:'-'}</td></tr>`}).join('')}</table></div>`;
  if(c.tipo==='gko'){h+=`<h3>Fase de grupos</h3><div class="g2" style="grid-template-columns:repeat(auto-fit,minmax(420px,1fr))">${c.grupos.map((gr,i)=>`<div><div class="muted" style="font-weight:700;margin:4px 0">Grupo ${String.fromCharCode(65+i)}</div><div class="tw"><table><tr><th>#</th><th>Club</th><th>PJ</th><th>DG</th><th>Pts</th></tr>${CP.tablaGrupo(gr).map((r,j)=>`<tr class="${j<2?'zup':''} ${r.id==u?'hl':''}"><td>${j+1}</td><td>${this.bd(r.id)} ${cn(r.id)}</td><td>${r.pj}</td><td>${r.gf-r.gc}</td><td><b>${r.pts}</b></td></tr>`).join('')}</table></div></div>`).join('')}</div>`}
  for(const [i,r] of [...c.rondas.entries()].reverse()){const open=i===c.rondas.length-1||r.ties.some(t=>t.a===u||t.b===u);h+=`<details class="rd" ${open?'open':''}><summary>${r.nombre} <small class="muted">(${r.ties.length} ${r.ties.length>1?'cruces':'cruce'}${r.legs>1?', ida y vuelta':''})</small></summary>${r.ties.map(t=>this.tieRow(t)).join('')}</details>`}
  return h}
 v_historia(){const g=this.g,c=g.clubs[g.userClubId],cum=[0],sz=Object.values(g.leagues).map(l=>l.ids.length);sz.forEach((n,i)=>cum.push(cum[i]+n));
  const lab=g.carrera.map(x=>x.y),gp=g.carrera.map(x=>cum[x.nivel-1]+x.pos),n=g.league.ids.length;
  return`<h2>Historia y gráficos</h2><div class="g2"><div class="card"><h4>📊 Posición por jornada</h4>${CH.line({series:[{name:'Posición',data:g.curva.pos}],labels:g.curva.pos.map((_,i)=>i+1),inv:true,min:1,max:n,fmt:v=>Math.round(v)+'º'})}</div><div class="card"><h4>💵 Presupuesto en la temporada</h4>${CH.line({series:[{name:'Presupuesto',data:g.curva.pres,area:true}],labels:g.curva.pres.map((_,i)=>i+1),fmt:v=>fmt(v)})}</div>
  <div class="card"><h4>🧭 Trayectoria (puesto general en el fútbol de ${g.pais.nombre})</h4>${CH.line({series:[{name:'Puesto global',data:gp}],labels:lab,inv:true,min:1,max:cum.at(-1),fmt:v=>Math.round(v)+'º'})}<p class="hint">1 = campeón de Primera; ${cum.at(-1)} = último de la categoría más baja.</p></div>
  <div class="card"><h4>💰 Ingresos y gastos por temporada</h4>${CH.bars({cats:g.finHist.map(h=>h.y),series:[{name:'Ingresos',color:'var(--ok)',data:g.finHist.map(h=>Object.values(h.ing).reduce((s,x)=>s+x,0))},{name:'Gastos',color:'var(--bad)',data:g.finHist.map(h=>Object.values(h.gas).reduce((s,x)=>s+x,0))}],fmt:v=>fmt(v)})}</div></div>
  <h3>Tu carrera</h3>${g.carrera.length?`<div class="tw"><table><tr><th>Temp.</th><th>Liga</th><th>Pos</th><th>Pts</th><th>${CP.NOMBRES.copa}</th><th>${CP.NOMBRES.lib}</th><th>${CP.NOMBRES.sud}</th></tr>${[...g.carrera].reverse().map(x=>`<tr><td>${x.y}</td><td>${x.liga}</td><td><b>${x.pos}º</b></td><td>${x.pts}</td><td>${x.copa}</td><td>${x.lib}</td><td>${x.sud}</td></tr>`).join('')}</table></div>`:'<p class="muted">Se arma al cerrar la primera temporada.</p>'}
  <h3>Palmarés del fútbol de ${g.pais.nombre}</h3>${g.pal.length||g.hist.length?`<div class="tw"><table><tr><th>Temp.</th><th>Campeón de Primera</th><th>${CP.NOMBRES.copa}</th><th>${CP.NOMBRES.lib}</th><th>${CP.NOMBRES.sud}</th></tr>${[...g.hist].reverse().map(h=>{const p=g.pal.find(x=>x.y===h.y)||{};return`<tr><td>${h.y}</td><td>${h.camp}</td><td>${p.copa||'-'}</td><td>${p.lib||'-'}</td><td>${p.sud||'-'}</td></tr>`}).join('')}</table></div>`:'<p class="muted">Todavía no hay temporadas completas.</p>'}
  <h3>Máximos del club</h3>${(()=>{const sq=squadOf(g,c.id).filter(p=>p.gol);return sq.sort((a,b)=>b.gol-a.gol).slice(0,5).map(p=>`<div class="kv"><span><a class="plink" data-act="card" data-id="${p.id}">${p.nombre}</a></span><b>${p.gol} ${p.gol==1?'gol':'goles'}</b></div>`).join('')||'<p class="muted">Sin goles todavía.</p>'})()}`}
 calComps(){const g=this.g,rows=Object.values(g.comps).filter(c=>!c.omitida).flatMap(c=>CP.matchesUser(g,c).map(m=>({c,m}))).sort((a,b)=>a.m.date<b.m.date?-1:1);
  if(!rows.length)return'';return`<h3>Copas</h3><div class="tw"><table><tr><th>Fecha</th><th>Competición</th><th>Partido</th><th>Resultado</th></tr>${rows.map(({c,m})=>`<tr><td>${m.date}</td><td>${CP.NOMBRES[c.key]}</td><td>${this.tn(m.h)} vs ${this.tn(m.a)}</td><td>${m.done?m.hg+'-'+m.ag:'-'}</td></tr>`).join('')}</table></div>`}
 recard(id){const dl=document.getElementById('dlg');if(dl.open&&dl.querySelector('.pcard'))this.card(+id)}
 card(id){const g=this.g,p=g.players[id],dl=document.getElementById('dlg');if(!p)return;const v=S.vista(g,p),ex=v.exacto,c=g.clubs[p.clubId],mine=p.clubId==g.userClubId;
  const hist=[...(p.h||[]),[g.year,p.ovr,p.pot,p.pj||0,p.gol||0]],A=[['vel','Velocidad'],['ace','Aceleración'],['pas','Pase'],['tec','Técnica'],['tir','Tiro'],['def','Defensa'],['fis','Físico'],['res','Resistencia'],['men','Mental']];
  dl.innerHTML=`<div class="pcard"><div class="ph">${c?badge(c,52):''}<div><h3 style="margin:0;text-transform:none;font-size:20px;color:var(--t);display:block">${p.nombre}</h3><div>${chip(p.pos)} ${p.edad} años · ${c?c.nombre:'Libre'}</div></div></div>
  <div class="cards" style="grid-template-columns:repeat(3,1fr)"><div><b>OVR</b>${ex?p.ovr:S.txtOvr(v.ovr)}</div><div><b>Potencial</b>${ex?p.pot:S.txtOvr(v.pot)}</div><div><b>Valor</b>${fmt(p.val)}</div></div>
  <div class="g2" style="grid-template-columns:1fr 1fr">${ex?`<div>${CH.radar({labels:A.map(a=>a[0].toUpperCase()),values:A.map(a=>p[a[0]])})}</div><div>${A.map(a=>`<div class="kv"><span>${a[1]}</span>${AT(p[a[0]])}</div>`).join('')}</div>`:'<p class="muted" style="grid-column:1/-1">🌫️ No tenés información precisa de este jugador. Mandá un ojeador o seguilo para conocer sus atributos.</p>'}</div>
  <div class="kv"><span>Pie</span><b>${p.pie||'-'}</b></div><div class="kv"><span>Rasgo</span><b>${p.rasgo||'Ninguno'}</b></div><div class="kv"><span>Moral / Condición</span><b>${p.mor} / ${Math.round(p.cond)}</b></div><div class="kv"><span>Salario</span><b>${fmt(p.sal)}</b></div><div class="kv"><span>Contrato hasta</span><b>${p.contrato}</b></div><div class="kv"><span>Esta temporada</span><b>${p.pj||0} partidos · ${p.gol||0} goles</b></div>${p.lesion>0?`<div class="kv"><span>Lesión</span><b class="badc">${p.tipo||''} · ${p.lesion} días</b></div>`:''}
  ${ex&&hist.length>1?`<h4 style="margin-top:14px">Evolución</h4>${CH.line({series:[{name:'OVR',data:hist.map(h=>h[1])},{name:'Potencial',data:hist.map(h=>h[2]),color:'var(--warn)'}],labels:hist.map(h=>h[0]),w:520,h:190})}`:''}
  <form method="dialog"><p>${mine?`<button type="button" class="pri" data-act="renew" data-id="${p.id}">Renovar</button> `:''}<button type="button" data-act="follow" data-id="${p.id}">${g.seguir.includes(p.id)?'★ Dejar de seguir':'☆ Seguir'}</button> <button>Cerrar</button></p></form></div>`;if(dl.open)dl.close();dl.showModal()}
 v_guardar(){const g=this.g;let t='dark';try{t=localStorage.getItem('fm_theme')||'dark'}catch(e){}return`<h2>Partida y ajustes</h2><p><button class="pri" data-act="save">Guardar partida</button> <button data-act="load">Cargar partida</button> <button class="bad" data-act="new">Nueva partida</button></p><h3>Apariencia</h3><label style="max-width:280px">Tema<select data-chg="tema"><option value="dark" ${t=='dark'?'selected':''}>Oscuro vivo</option><option value="light" ${t=='light'?'selected':''}>Claro</option><option value="club" ${t=='club'?'selected':''}>Color del club</option></select></label><h3>Jugabilidad</h3><p><button data-act="fog">Niebla de información: ${g.fog?'activada':'desactivada'}</button></p><p class="hint">Con la niebla activada ves rangos estimados de los jugadores de otros clubes y los ojeadores los afinan. Desactivada, ves todo exacto.</p>`}
 act(a,d){const g=this.g;if(this.act9(a,d))return;switch(a){
  case'pick':this.game=Game.create(structuredClone(this.data),+d.id);this.view='inicio';this.render();break;
  case'load':{const s=load();if(s){this.game=s;this.view='inicio';this.go();this.toast('Partida cargada')}else this.toast('No hay partida guardada');break}
  case'nav':this.view=d.v;this.render();break;
  case'day':if(g.despedido)break;g.advanceDay();this.go();break;
  case'next':{if(g.despedido)break;let p;do{p=g.advanceDay()}while(!p&&!g.allDone);this.go();this.toast(g.news.at(-1));break}
  case'save':this.toast(save(g)?'Partida guardada':'No se pudo guardar');break;
  case'new':this.start();break;
  case'rep':this.report(+d.i);break;
  case'ctab':this.ct=d.k;this.render();break;
  case'card':this.card(+d.id);break;
  case'reprc':{const x=(g.reps||[]).find(x=>x.mid==+d.m&&x.key==d.k);if(x)this.reportR(x.r);break}
  case'auto':g.lineup=autoLineup(squadOf(g,g.userClubId),g.tactic.formacion,d.rot);this.render();break;
  case'buy':{const[ok,m,c]=T.buy(g,+d.id,+document.getElementById('o'+d.id).value);this.toast(!ok&&c&&confirm(m+'. ¿Aceptás?')?T.buy(g,+d.id,c)[1]:m);this.render();break}
  case'pickp':this.pk=this.pk==+d.id?null:+d.id;this.render();break;
  case'formsave':{const n=prompt('Nombre de la formación',g.tactic.formacion);if(n&&n.trim()){const name=n.trim(),sl=this.tp.slots.map(s=>({...s}));g.custom[name]=sl;setFormation(name,sl);g.tactic.formacion=name;this.render()}break}
  case'loan':this.toast(T.loan(g,+d.id)[1]);this.render();break;
  case'loanout':this.toast(T.loanOut(g,+d.id)[1]);this.render();break;
  case'offer':this.toast(T.answerOffer(g,+d.i,d.ok==='1'));this.render();break;
  case'obra':this.toast(F.mejorar(g,d.k));this.render();break;
  case'staffup':this.toast(F.mejorarStaff(g,d.k));this.render();break;
  case'sp_ok':this.toast(SP.aceptar(g,+d.id));this.render();break;
  case'sp_no':this.toast(SP.rechazar(g,+d.id));this.render();break;
  case'sp_neg':this.toast(SP.negociar(g,+d.id,+d.p));this.render();break;
  case'inv_ok':this.toast(IV.aceptar(g,+d.id));this.render();break;
  case'inv_no':this.toast(IV.rechazar(g,+d.id));this.render();break;
  case'inv_buy':if(confirm('¿Terminar este acuerdo pagando la compensación?'))this.toast(IV.recomprar(g,+d.id));this.render();break;
  case'sc_hire':this.toast(S.contratar(g)[1]);this.render();break;
  case'sc_fire':if(confirm('¿Despedir al ojeador?'))this.toast(S.despedir(g,+d.id));this.render();break;
  case'sc_cancel':S.cancelar(g,+d.id);this.render();break;
  case'sc_go':{const v=i=>document.getElementById(i+d.id).value;this.toast(S.mision(g,+d.id,{region:v('sr'),tipo:v('st'),linea:v('sl')})[1]);this.render();break}
  case'follow':S.seguir(g,+d.id);this.render();this.recard(d.id);break;
  case'promo':this.toast(S.ficharPromesa(g,+d.id)[1]);this.render();break;
  case'fog':g.fog=!g.fog;this.render();break;
  case'livetog':g.live=!g.live;this.render();break;
  case'lp':this.run=!this.run;if(this.run)this.tick();else this.renderLive();break;
  case'lf':this.speed=this.speed>200?120:500;this.renderLive();break;
  case'lsub':this.toast(this.lm.sub(this.us,document.getElementById('sOut').value,document.getElementById('sIn').value)?'Cambio hecho':'Cambio no válido');this.renderLive();break;
  case'lend':while(this.lm.min<90)this.lm.step();this.endLive();break;
  case'endseason':endSeason(g);this.view='inicio';this.render();this.toast('Comienza la temporada '+g.year);break;
  case'renew':this.toast(renew(g,g.players[d.id]));this.render();this.recard(d.id);break;
  case'sell':{const o=T.sellOffer(g,+d.id),p=g.players[d.id];if(!o)this.toast('Sin ofertas o plantilla mínima (16)');else if(confirm(`${this.tn(o.to)} ofrece ${fmt(o.price)} por ${p.nombre}. ¿Vender?`))this.toast(T.sell(g,p.id,o)[1]);this.render();break}}}
 chg(a,d,v){const g=this.g;if(this.chg9(a,d,v))return;if(a==='precio'){g.clubs[g.userClubId].precio=+v;return this.render()}if(a==='tema'){try{localStorage.setItem('fm_theme',v)}catch(e){}return this.render()}if(a==='sd'){this.sd=v;return this.start()}if(a==='lv'){this.lv=v;return this.render()}if(a==='ltac'){g.tactic[d.k]=v;this.lm.recalc();return this.renderLive()}
  if(a==='form'){g.tactic.formacion=v;g.lineup=autoLineup(squadOf(g,g.userClubId),v)}
  else if(a==='tac')g.tactic[d.k]=v;
  else if(a==='slot'){const[t,i]=d.s.split(':'),L=g.lineup,arr=[L.xi,L.bench],A=t==='xi'?L.xi:L.bench;v=+v;for(const X of arr){const j=X.indexOf(v);if(j>=0)X[j]=A[i]}A[i]=v}
  else if(a==='f')this.f[d.k]=v;else if(a==='train')g.training=v;else if(a==='jr')this.jr=+v;
  this.render()}
 initTP(){const g=this.g,cv=document.getElementById('tp');if(!cv)return;this.tp={slots:coords(g.tactic.formacion).map(s=>({...s}))};
  const board=tacticBoard(cv,()=>({slots:this.tp.slots,xi:g.lineup.xi.map(i=>g.players[i]),labels:FORMATIONS[g.tactic.formacion]}),{
   move:(i,x,y,done)=>{this.tp.slots[i].x=x;this.tp.slots[i].y=y;if(!done)return board.draw();let n=g.tactic.formacion;if(!g.custom[n]){n='Personalizada '+(Object.keys(g.custom).length+1);g.tactic.formacion=n}
    g.custom[n]=this.tp.slots.map(s=>({...s}));setFormation(n,g.custom[n]);this.render()},
   click:i=>{if(this.pk){const id=this.pk;this.pk=null;this.chg('slot',{s:'xi:'+i},id)}}});board.draw()}
 go(){this.g.pend?this.live():this.render()}
 live(){const g=this.g,m=g.pend.m;if(!this.lm){this.us=m.h==g.userClubId?0:1;this.lm=new LiveMatch(g.setup(m.h),g.setup(m.a));this.lm.auto[this.us]=false;this.run=false;this.ht=0;this.speed=500;this.el.innerHTML='<main class="live"><div id="lvs"></div><p><button data-act="lp" id="lvp"></button> <button data-act="lf" id="lvf"></button> <button data-act="lend">Simular hasta el final</button></p><canvas id="pitch" width="900" height="580"></canvas><div id="lvc"></div><div class="ev" id="lvlog"></div></main>';this.pitch=new Pitch(document.getElementById('pitch'),this.lm,this.us);this.renderLive();this._lt=setTimeout(()=>this.tick(),this.speed);return}this.renderLive()}
 tick(){clearTimeout(this._lt);if(!this.run)return;const lm=this.lm;lm.step();this.pitch.update();this.renderLive();if(lm.min>=90)return this.endLive();if(lm.min===45&&!this.ht){this.ht=1;this.run=false;this.renderLive();return}this._lt=setTimeout(()=>this.tick(),this.speed)}
 endLive(){const g=this.g;clearTimeout(this._lt);this.pitch.stop=true;const wasComp=g.pend.kind==='comp';g.finishLive(this.lm.result());this.lm=null;this.view='inicio';this.render();if(wasComp&&g.lastRep)this.reportR(g.lastRep);else this.report(g.league.results.length-1)}
 renderLive(){const lm=this.lm,g=this.g,T=lm.T,st=lm.st,t=this.us,n=i=>T[i].club.nombre,paused=!this.run,pc=i=>Math.round(st[i].poss/(lm.min||1)*100),
  sel=k=>`<label>${LBL[k]}<select data-chg="ltac" data-k="${k}">${opts(OPTIONS[k],g.tactic[k])}</select></label>`,
  ctl=paused?`<div class="grid">${Object.keys(OPTIONS).map(sel).join('')}</div><div class="grid"><label>Sale<select id="sOut">${lm.live(t).map(p=>`<option value="${p.id}">${p.pos} ${p.nombre} (cond ${Math.round(p.cond)})</option>`).join('')}</select></label><label>Entra<select id="sIn">${T[t].bench.filter(p=>!lm.played[t].has(p.id)).map(p=>`<option value="${p.id}">${p.pos} ${p.nombre} (${p.ovr})</option>`).join('')}</select></label></div><p>Cambios usados: ${lm.subs[t]}/5 <button data-act="lsub">Hacer cambio</button></p>`:'',$=id=>document.getElementById(id);
  $('lvs').innerHTML=`<div class="score">${badge(T[0].club,34)} <b>${n(0)}</b> <span>${st[0].goals} - ${st[1].goals}</span> <b>${n(1)}</b> ${badge(T[1].club,34)}</div><p>Minuto ${lm.min} · Posesión ${pc(0)}% - ${pc(1)}% · Tiros ${st[0].shots}-${st[1].shots} · Al arco ${st[0].sot}-${st[1].sot}</p>`;
  $('lvp').textContent=paused?'Seguir':'Pausar';$('lvf').textContent='Velocidad: '+(this.speed>200?'normal':'rápida');if($('lvc').innerHTML!==ctl)$('lvc').innerHTML=ctl;
  $('lvlog').innerHTML=[...lm.ev].reverse().map(e=>`<div class="${e.t}">MIN ${e.min} — ${e.txt}</div>`).join('')}
 resRow(r,i){return`<div class="res">J${r.j} · <b>${this.tn(r.h)} ${r.hg} - ${r.ag} ${this.tn(r.a)}</b> <button data-act="rep" data-i="${i}">Ver</button></div>`}
 report(i){this.reportR(this.g.league.results[i])}
 reportR(r){const s=r.st,n=id=>this.tn(id),dl=document.getElementById('dlg'),row=(l,k,f=x=>x)=>`<tr><td>${f(s[0][k])}</td><th>${l}</th><td>${f(s[1][k])}</td></tr>`;
  dl.innerHTML=`<h3>${n(r.h)} ${r.hg} - ${r.ag} ${n(r.a)}</h3><small>Jornada ${r.j} · ${r.date}</small><table class="stats">${row('Posesión','poss',x=>x+'%')}${row('Tiros','shots')}${row('Al arco','sot')}${row('Faltas','fouls')}${row('Amarillas','yel')}${row('Rojas','red')}${row('Córners','corners')}</table><h4>Crónica</h4><div class="ev">${r.ev.map(e=>`<div class="${e.t}">MIN ${e.min} — ${e.txt}</div>`).join('')}<b>FINAL ${n(r.h)} ${r.hg} - ${r.ag} ${n(r.a)}</b></div><h4>Jugadores destacados</h4>${r.top.map(p=>`<div>${p.n} (${n(p.c)}) — ${p.r.toFixed(1)}</div>`).join('')}<form method="dialog"><p><button>Cerrar</button></p></form>`;dl.showModal()}
 v_tacticas(){const g=this.g,t=g.tactic,sq=squadOf(g,g.userClubId),
  sel=(s,id,l)=>`<label>${l}<select data-chg="slot" data-s="${s}">${sq.map(p=>`<option value="${p.id}" ${p.id==id?'selected':''}>${p.pos} ${p.nombre} (${p.ovr}${p.lesion>0?' 🩹':''})</option>`).join('')}</select></label>`;
  return`<h2>Tácticas</h2><div class="grid"><label>Formación<select data-chg="form">${opts(Object.keys(FORMATIONS),t.formacion)}</select></label>${Object.keys(OPTIONS).map(k=>`<label>${LBL[k]}<select data-chg="tac" data-k="${k}">${opts(OPTIONS[k],t[k])}</select></label>`).join('')}</div><h3>Pizarra</h3><div class="tpitch"><div><canvas id="tp" width="900" height="580"></canvas><p class="hint">Arrastrá un círculo para cambiar de posición a ese jugador. Elegí a alguien de la lista y tocá un círculo para ponerlo ahí. Verde: en su puesto · Amarillo: misma línea · Rojo: fuera de posición.</p></div><div class="plist">${sq.map(p=>`<div class="pl${p.id==this.pk?' on':''}" data-act="pickp" data-id="${p.id}">${g.lineup.xi.includes(p.id)?'●':g.lineup.bench.includes(p.id)?'○':'·'} <b>${p.pos}</b> ${p.nombre}${p.lesion>0?' 🩹':''}<span>${p.ovr} · ${Math.round(p.cond)}%</span></div>`).join('')}</div></div><h3>Suplentes</h3><div class="grid">${g.lineup.bench.map((id,i)=>sel('bench:'+i,id,'Banco '+(i+1))).join('')}</div><p><button data-act="auto">Elegir el mejor equipo</button> <button data-act="auto" data-rot="1">Elegir rotando cansados</button> <button data-act="formsave">Guardar formación como…</button></p>`}
 v_calendario(){const g=this.g,id=g.userClubId,L=g.league;return`<h2>Calendario</h2><table><tr><th>J</th><th>Fecha</th><th>Partido</th><th>Resultado</th></tr>${L.fixtures.map((fx,i)=>{const m=fx.find(x=>x.h==id||x.a==id);if(!m)return`<tr><td>${i+1}</td><td>${L.date(i)}</td><td>Libre</td><td>-</td></tr>`;const ri=L.results.findIndex(r=>r.j==i+1&&r.h==m.h),r=L.results[ri];return`<tr class="${i==L.j?'hl':''}"><td>${i+1}</td><td>${L.date(i)}</td><td>${this.tn(m.h)} vs ${this.tn(m.a)}</td><td>${r?`${r.hg}-${r.ag} <button data-act="rep" data-i="${ri}">Ver</button>`:'-'}</td></tr>`}).join('')}</table>${this.calComps()}`}
 v_resultados(){const L=this.g.league,j=this.jr||L.j;if(!j)return'<h2>Resultados</h2><p>Todavía no se jugó ninguna jornada.</p>';return`<h2>Resultados</h2><label>Jornada<select data-chg="jr">${Array.from({length:L.j},(_,i)=>`<option ${i+1==j?'selected':''}>${i+1}</option>`).join('')}</select></label>${L.results.map((r,i)=>r.j==j?this.resRow(r,i):'').join('')}`}
 v_entrenamiento(){const g=this.g,sq=squadOf(g,g.userClubId);return`<h2>Entrenamiento</h2><label>Foco<select data-chg="train">${opts(['Equilibrado','Físico','Técnico','Descanso'],g.training)}</select></label><p>Condición media: ${Math.round(sq.reduce((s,p)=>s+p.cond,0)/sq.length)}% · Lesionados: ${sq.filter(p=>p.lesion>0).length}</p><p>Físico mejora físico, resistencia y velocidad. Técnico mejora técnica, pase y tiro. Descanso acelera la recuperación.</p>`}
}
U9.install(UI,{pTable,chip,AT,bar,opts,dias,S});
U10.install(UI,{pTable,chip,AT,bar,opts,dias,S});
PD.install(UI,{pips});
MU.install(UI);
PRM.install(UI);
